[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd server && npm install',
  'npm install'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'cd server && node index.js'

